name: ezopsworkflowtest

on:  [ 'push' ]

# CI - build, teste, e upload de artefato
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.2]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      #pulado teste pois não consegui implementa (comando npm test não parava)
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ezops-artifact
          path: /home/runner/work/ezops-test-jhonatanaguiar
  
# CDelivery - criando imagem docker do artefato criado
  docker-image:
     needs: [build]
     
     runs-on: ubuntu-latest
     steps:

     - uses: actions/checkout@v2

     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         name: ezops-artifact
         path: ezops-test-jhonatanaguiar

     - name: Login to DockerHub Registry
       uses: docker/login-action@v1
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

     - name: Build doker image and push
       env:
        IMAGE_NAME: jhonyra/ezops-docker-image
        IMAGE_TAG: latest
       run: |
         docker build -t $IMAGE_NAME:$IMAGE_TAG .
         docker push $IMAGE_NAME:$IMAGE_TAG
         
#CDeployment - subindo imagem docker na aws
  deploy-on-aws:
     needs: [docker-image]
     
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2
      
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: i-050a7cc7ebf89fe25

          working-directory: /home/ubuntu/
          command: |
              sudo docker pull jhonyra/ezops-docker-image:latest
              sudo docker run -p 3000:3000 -d jhonyra/ezops-docker-image:latest
        
          # Catch SSM outputs
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
