name: ezopsworkflowtest

on:  [ 'push' ]

# CI - build, teste, e upload de artefato
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.2]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      #pulado teste pois não consegui implementa (comando npm test não parava)
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ezops-artifact
          path: ezops-test-jhonatanaguiar
  
# CDelivery - criando imagem docker do artefato criado
