name: ezops-app-3001

on:  
  push:
    branches: [ 3001/main-server ]
  pull_request:
    branches: [ 3001/main-server ]
    
#CDeployment - fetch no repositório e reiniciando aplicação
jobs:
  deployment:
  
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2
      
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@release
        
        with:
          command: |
              git pull origin main-alternative
              pm2 restart ezops-test
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.REMOTE_SSH_KEY }}
